# Exercise 1: Create and Reshape a NumPy Array

### Steps:
1. Import NumPy.
2. Create an array from 1 to 10.
3. Reshape it into a 2×5 matrix.

In [1]:
import numpy as np

In [2]:
# Step 1: Create an array from 1 to 10
arr = np.arange(1, 11)

In [3]:
# Step 2: Reshape into a 2x5 matrix
reshaped_arr = arr.reshape(2, 5)

In [4]:
# Display the reshaped array
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Exercise 2: Extract Elements from an Array

### Steps:
1. Create an array from 1 to 20.
2. Extract elements between the 5th and 15th index.

In [5]:
# Step 1: Create an array from 1 to 20
arr = np.arange(1, 21)

# Step 2: Extract elements between index 5 and 15
extracted_elements = arr[5:16]

# Display extracted elements
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


# Exercise 3: Create and Modify a Pandas Series

Steps:
1. Import Pandas.
2. Create a Pandas Series.
3. Add a new item 'pears': 4.

In [6]:
import pandas as pd

# Step 1: Create a Pandas Series
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Step 2: Add a new item
fruits['pears'] = 4

# Display the updated series
print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# Exercise 4: Create a DataFrame

### Steps:
1. Create a Pandas DataFrame with columns: name, age, gender.
2. Add 10 rows of data.

In [7]:
# Step 1: Create a DataFrame with 10 rows
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 29, 31, 27, 26],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   28      M
4      Eve   35      F
5    Frank   40      M
6    Grace   29      F
7   Hannah   31      F
8      Ian   27      M
9     Jack   26      M


# Exercise 5: Add a New Column to the DataFrame

### Steps:
1. Add a new column "occupation" with values.

In [8]:
# Step 1: Add a new column "occupation"
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

# Display the updated DataFrame
print(df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   28      M  Programmer
4      Eve   35      F     Manager
5    Frank   40      M     Analyst
6    Grace   29      F  Programmer
7   Hannah   31      F     Manager
8      Ian   27      M     Analyst
9     Jack   26      M  Programmer


# Exercise 6: Select Rows Where Age ≥ 30

### Steps:
1. Filter rows where age ≥ 30.

In [9]:
# Step 1: Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]

# Display the filtered DataFrame
print(filtered_df)


     name  age gender occupation
1     Bob   30      M    Manager
4     Eve   35      F    Manager
5   Frank   40      M    Analyst
7  Hannah   31      F    Manager


# Exercise 7: Save and Read CSV File

### Steps:
1. Save the DataFrame as a CSV file.
2. Read the CSV file.
3. Display the contents.

In [10]:
# Step 1: Save DataFrame as CSV
df.to_csv('people_data.csv', index=False)

# Step 2: Read the CSV file
df_csv = pd.read_csv('people_data.csv')

# Step 3: Display the contents
print(df_csv)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   28      M  Programmer
4      Eve   35      F     Manager
5    Frank   40      M     Analyst
6    Grace   29      F  Programmer
7   Hannah   31      F     Manager
8      Ian   27      M     Analyst
9     Jack   26      M  Programmer
